debug: env
default:
  avatar: volantis-static/media/placeholder/avatar/round/3442075.svg
  link: volantis-static/media/placeholder/link/8f277b4ee0ecd.svg
  cover: volantis-static/media/placeholder/cover/76b86c0226ffd.svg
  image: volantis-static/media/placeholder/image/2659360.svg
csp:
  enable: true
  content: |
    default-src 'self' https:;
    block-all-mixed-content;
    base-uri 'self' https:;
    form-action 'self' https:;
    worker-src 'self' https:;
    connect-src 'self' https: *;
    img-src 'self' data: https: *;
    media-src 'self' https: *;
    font-src 'self' data: https: *;
    frame-src 'self' https: *;
    manifest-src 'self' https: *;
    child-src https:;
    script-src 'self' https: 'unsafe-inline' 'unsafe-eval' *;
    style-src 'self' https: 'unsafe-inline' *;
cdn:
  enable: true
  use: jsdelivr
cdn_version: true
volantis_static_cdn: https://cdn.jsdelivr.net/npm/volantis-static@latest/
# volantis_static_cdn: https://unpkg.com/volantis-static@0.0.1654736714924/
content_visibility: false
replace:
  - https://cdn.jsdelivr.net/npm/ => https://unpkg.com/
  - https://cdn.jsdelivr.net/gh/ => https://gcore.jsdelivr.net/gh/
dns_prefetch:
  - https://unpkg.com
scroll_smooth: true
navbar:
  visiable: auto
  logo:

  menu:
    - name: 博客
      icon: fa-solid fa-rss
      url: /
    - name: 分类
      icon: fa-solid fa-folder-open
      url: categories/
    - name: 标签
      icon: fa-solid fa-tags
      url: tags/
    - name: 归档
      icon: fa-solid fa-archive
      url: archives/
    - name: 友链
      icon: fa-solid fa-link
      url: friends/
    - name: 关于
      icon: fa-solid fa-info-circle
      url: about/
    - name: 暗黑模式
      icon: fa-solid fa-moon
      toggle: darkmode
  search: Search...
cover:
  height_scheme: full
  layout_scheme: search
  display:
    home: true
    archive: true
    others: false
  background: https://i.postimg.cc/cLS9Fh3b/wallhaven-k8wdv6-1920x1080.png
  title: 'Volantis'
  subtitle: ''
  search: 搜索一下
  features:
    - name: 分类
      url: categories/
    - name: 标签
      url: tags/
    - name: 归档
      url: archives/
    - name: 关于
      url: /about/
pages:
  friends:
    layout_scheme: traditional
article:
  preview:
    scheme: landscape
    pin_icon: volantis-static/media/twemoji/assets/svg/1f4cc.svg
    auto_title: true
    auto_excerpt: true
    author: false
    readmore: auto
  body:
    top_meta: [author, category, date, counter]
    bottom_meta: [updated, tags, share]
    footer_widget:
      references:
        title: 参考资料
        icon: fa-solid fa-quote-left
      related_posts:
        enable: false
      copyright:
        enable: false
    meta_library:
      author:
        avatar: volantis-static/media/org.volantis/blog/favicon/apple-touch-icon.png
        name: 请设置文章作者
        url: /
      date:
        icon: fa-solid fa-calendar-alt
        title: '发布于：'
        format: 'll'
      updated:
        icon: fa-solid fa-edit
        title: '更新于：'
        format: 'll'
      counter:
        icon: fa-solid fa-eye
        unit: '次浏览'
      walinecount:
        icon: fa-solid fa-comment-dots
        desc: '条评论'
      tags:
        icon: fa-solid fa-hashtag
      share:
        - id: qq
          img: volantis-static/media/org.volantis/logo/128/qq.png
        - id: qzone
          img: volantis-static/media/org.volantis/logo/128/qzone.png
        - id: weibo
          img: volantis-static/media/org.volantis/logo/128/weibo.png
comments:
  title: <i class='fa-solid fa-comments'></i> 评论
  service: livere 
  livere:
    uid: MTAyMC82MDgwNS8zNzI3NQ==
sidebar:
  position: right
  for_page: [blogger, category, tagcloud, donate]
  for_post: [toc]
  widget_library:
    blogger:
      class: blogger
      display: [desktop, mobile]
      avatar: https://i.postimg.cc/Bn2W6tTd/0cdd3d3af11da635bae8ac1b32495f800516f739.jpg
      shape: rectangle
      url: /about/
      title: dajiahao
      jinrishici: true
      social:
        - icon: fa-solid fa-rss
          url: /atom.xml
        - icon: fa-solid fa-envelope
          url: mailto:2109544755@qq.com
        - icon: fab fa-github
          url: https://github.com/volantis-x/
    toc:
      class: toc
      display: [desktop, mobile]
      sticky: true
      header:
        icon: fa-solid fa-list
        title: 本文目录
      list_number: false
      min_depth: 2
      max_depth: 5
    category:
      class: category
      display: [desktop]
      header:
        icon: fa-solid fa-folder-open
        title: 文章分类
        url: /blog/categories/
    tagcloud:
      class: tagcloud
      display: [desktop, mobile]
      header:
        icon: fa-solid fa-tags
        title: 热门标签
        url: /blog/tags/
      min_font: 14
      max_font: 24
      color: true
      start_color: '#999'
      end_color: '#555'
    webinfo:
      class: webinfo
      display: [desktop]
      header:
        icon: fa-solid fa-award
        title: 站点信息
      type:
        article:
          enable: true
          text: '文章数目：'
          unit: '篇'
        runtime:
          enable: true
          data: '2025/07/12'
          text: '已运行时间：'
          unit: '天'
        wordcount:
          enable: true
          text: '本站总字数：'
          unit: '字'
        visitcounter:
          siteuv:
            enable: true
            text: '本站访客数：'
            unit: '人'
          sitepv:
            enable: true
            text: '本站总访问量：'
            unit: '次'
        lastupd:
          enable: true
          friendlyShow: true
          text: '最后活动时间：'
          unit: '日'
tag_plugins:
  note:
    icon: '\f054'
  checkbox:
    interactive: false
  link:
    placeholder: volantis-static/media/org.volantis/logo/256/safari.png
site_footer:
  layout: [aplayer, social, license,copyright, custom]  # 增加custom
  custom: |
    <script async src="https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>
  social:
    - icon: fa-solid fa-rss
  source: https://github.com/volantis-x/volantis-docs/
  analytics: |
    <span id="busuanzi_container_site_pv">本站总访问量 <span id="busuanzi_value_site_pv"><i class="fa-solid fa-loader fa-spin fa-fw" aria-hidden="true"></i></span> 次</span>
    <span id="busuanzi_container_site_uv">访客数 <span id="busuanzi_value_site_uv"><i class="fa-solid fa-loader fa-spin fa-fw" aria-hidden="true"></i></span> 人</span>
  copyright: '[Copyright © since 2017 Hexo. All rights reserved.](/)'
  br: '<br>'
plugins:
  globalJquery: true
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  jquery: volantis-static/libs/jquery/dist/jquery.min.js
  fontawesome: volantis-static/libs/@fortawesome/fontawesome-free/css/all.min.css
  katex:
    js: volantis-static/libs/katex/katex.min.js
    css: volantis-static/libs/katex/katex.min.css
    render: volantis-static/libs/katex/contrib/auto-render.min.js
  mathjax: volantis-static/libs/mathjax/es5/tex-mml-chtml.js
  markdown: volantis-static/libs/github-markdown-css/github-markdown.css
  marked: volantis-static/libs/marked/marked.min.js
  hlsjs: volantis-static/libs/hls.js/dist/hls.min.js
  fancybox:
    css: volantis-static/libs/@fancyapps/ui/dist/fancybox.css
    js: volantis-static/libs/@fancyapps/ui/dist/fancybox.umd.js
  sitesjs:
    enable: true
  friendsjs:
    enable: true
  contributorsjs:
    enable: true
  preload:
    enable: true
    service: flying_pages
    flying_pages: volantis-static/libs/flying-pages/flying-pages.min.js
  lazyload:
    enable: true
    js: volantis-static/libs/vanilla-lazyload/dist/lazyload.min.js
    blurIn: true
  code_highlight: highlightjs
  highlightjs:
    copy_code: true
  scrollreveal:
    enable: true
    js: volantis-static/libs/scrollreveal/dist/scrollreveal.min.js
    distance: 32px
    duration: 800
    interval: 20
    scale: 0.95
  wordcount:
    enable: true
  nodewaves:
    enable: true
    css: volantis-static/libs/node-waves/dist/waves.min.css
    js: volantis-static/libs/node-waves/dist/waves.min.js
  fontawesome_animation:
    enable: true
    css: volantis-static/libs/font-awesome-animation/font-awesome-animation.min.css
  comment_typing:
    enable: true
    js: volantis-static/libs/comment_typing/comment_typing.js
  parallax:
    enable: true
    position: cover
    shuffle: true
    duration: 10000
    fade: 1500
    images:
      - volantis-static/media/wallpaper/minimalist/2020/001.webp
      - volantis-static/media/wallpaper/minimalist/2020/002.webp
      - volantis-static/media/wallpaper/minimalist/2020/003.webp
      - volantis-static/media/wallpaper/minimalist/2020/004.webp
      - volantis-static/media/wallpaper/minimalist/2020/005.webp
      - volantis-static/media/wallpaper/minimalist/2020/006.webp
      - volantis-static/media/wallpaper/minimalist/2020/012.webp
      - volantis-static/media/wallpaper/minimalist/2020/016.webp
      - volantis-static/media/wallpaper/minimalist/2020/019.webp
      - volantis-static/media/wallpaper/minimalist/2020/025.webp
      - volantis-static/media/wallpaper/minimalist/2020/033.webp
      - volantis-static/media/wallpaper/minimalist/2020/034.webp
      - volantis-static/media/wallpaper/minimalist/2020/035.webp
      - volantis-static/media/wallpaper/minimalist/2020/038.webp
      - volantis-static/media/wallpaper/minimalist/2020/039.webp
      - volantis-static/media/wallpaper/minimalist/2020/042.webp
      - volantis-static/media/wallpaper/minimalist/2020/046.webp
      - volantis-static/media/wallpaper/minimalist/2020/051.webp
      - volantis-static/media/wallpaper/minimalist/2020/052.webp
      - volantis-static/media/wallpaper/minimalist/2020/054.webp
      - volantis-static/media/wallpaper/minimalist/2020/056.webp
  aplayer:
    enable: true
    js:
      aplayer: volantis-static/libs/aplayer/dist/APlayer.min.js
      meting: volantis-static/libs/meting/dist/Meting.min.js
    css: volantis-static/libs/aplayer/dist/APlayer.min.css
    server: netease
    type: playlist
    id: 9102149205
    fixed: true
    theme: '#1BCDFC'
    autoplay: false
    order: list
    loop: all
    volume: 0.7
    list_max_height: 320px
    list_folded: true
    autoHide: true
  pjax:
    js: volantis-static/libs/pjax/pjax.min.js
    enable: true
    cover: true
    timeout: 20000
    animation: false
  darkmode:
    enable: true
  killOldVersionsOfIE:
    enable: true
  killNoScript:
    enable: true
  message:
    enable: true
    css: volantis-static/libs/izitoast/dist/css/iziToast.min.css
    js: volantis-static/libs/izitoast/dist/js/iziToast.min.js
    icon:
      default: fa-solid fa-info-circle light-blue
      quection: fa-solid fa-question-circle light-blue
    time:
      default: 5000
      quection: 20000
    position: 'topRight'
    transitionIn: 'bounceInLeft'
    transitionOut: 'fadeOutRight'
    titleColor: 'var(--color-text)'
    messageColor: 'var(--color-text)'
    backgroundColor: 'var(--color-card)'
    copyright:
      enable: true
      title: '知识共享许可协议'
      message: '请遵守 CC BY-NC-SA 4.0 协议。'
      icon: 'far fa-copyright light-blue'
    aplayer:
      enable: true
      play: fa-solid fa-play
      pause: fa-solid fa-pause
  swiper:
    enable: true
    css: volantis-static/libs/swiper/swiper-bundle.min.css
    js: volantis-static/libs/swiper/swiper-bundle.min.js
rightmenu:
  enable: true
color_scheme:
  common:
    theme: '#3A9FBF'
    link: '#2092ec'
    button: '#44D7B6'
    hover: '#FF7B54'
    inner: '#fff'
    selection: 'alpha(#2196f3, 0.2)'
  light:
    site_bg: '#F8F9FA'
    site_inner: '#fff'
    site_footer: '#666'
    card: '#FFFFFF'
    text: '#444'
    block: '#f6f6f6'
    codeblock: '#FFF7EA'
    inlinecode: '#c74f00'
    h1: '#3a3a3a'
    h2: '#3a3a3a'
    h3: '#333'
    h4: '#444'
    h5: '#555'
    h6: '#666'
    p: '#444'
    list: '#666'
    list_hl: 'mix($color-theme, #000, 80)'
    meta: '#888'
    copyright_bkg: '#f5f5f5'
  dark:
    site_bd: '#121212'
    site_bg: '#1f1f1f'
    card: '#1E2A38'
    site_inner: '#eeeeeede'
    site_footer: '#aaaaaade'
    text: '#E6EDF4'
    block: '#434343'
    codeblock: '#1f1f1f'
    inlinecode: '#D56D28'
    h1: '#FFFFFFde'
    h2: '#FFFFFFde'
    h3: '#FFFFFF99'
    h4: '#FFFFFF99'
    h5: '#FFFFFF99'
    h6: '#FFFFFF99'
    p: '#d9d9d9de'
    list: '#d9d9d9de'
    list_hl: 'mix($color-theme, #fff, 80)'
    meta: '#bfbfbfde'
    copyright_bkg: '#21252b'
    brightness: 70%
custom_css:
  font_smoothing: true
  max_width: 1080px
  scrollbar:
    size: 4px
    border: 2px
    background: rgb(84,181,160) linear-gradient(45deg, rgba(255, 255, 255, 0.4) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.4) 50%, rgba(255, 255, 255, 0.4) 75%, transparent 75%, transparent)
    hover_background: rgb(84,181,160) linear-gradient(45deg, rgba(255, 255, 255, 0.4) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.4) 50%, rgba(255, 255, 255, 0.4) 75%, transparent 75%, transparent)
  navbar:
    height: 64px
    effect: [shadow, floatable, blur]
  sidebar:
    effect: [shadow, floatable, blur]
  body:
    effect: [shadow, floatable, blur]
    highlight:
      language: true
      grayscale: true
    text_align:
      h1: left
      h2: left
      h3: left
      h4: left
      p: justify
  gap:
    h2: 48px
    h3: 24px
    h4: 16px
    p: 1.2em
    line_height: 1.75
  border_radius:
    card: 12px
    codeblock: 4px
    searchbar: 8px
    button: 6px
  fontsize:
    root: 16px
    h1: 1.5rem
    h2: 1.5rem
    h3: 1.25rem
    h4: 1.125rem
    h5: 1rem
    h6: 1rem
    list: .9375rem
    meta: 0.9rem
    code: .8125rem
    footnote: .78125rem
  fontfamily:
    logofont:
      fontfamily: '"Varela Round", "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'Varela Round'
      url: volantis-static/media/fonts/VarelaRound/VarelaRound-Regular.ttf
      weight: normal
      style: normal
    bodyfont:
      fontfamily: 'UbuntuMono, "Varela Round", "PingFang SC", "Microsoft YaHei", Helvetica, Arial'
      name: 'UbuntuMono'
      url: volantis-static/media/fonts/UbuntuMono/UbuntuMono-Regular.ttf
      weight: normal
      style: normal
analytics:
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
seo:
  use_tags_as_keywords: true
  use_excerpt_as_description: true
  robots:
    home_first_page: index,follow
    home_other_pages: noindex,follow
    archive: noindex,follow
    category: noindex,follow
    tag: noindex,follow
open_graph:
  image: volantis-static/media/org.volantis/blog/favicon/android-chrome-192x192.png
  twitter_card: summary
structured_data:
  enable: true
  data:
    person:
      sns:
        - https://github.com/volantis-x
    logo:
      path: volantis-static/media/org.volantis/blog/favicon/android-chrome-192x192.png
      width: 192
      height: 192